# SPDX-FileCopyrightText: (c) 2025 Trailblaze Software, all rights reserved
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; version 2.1.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# For LGPL2 incompatible licensing or development requests, please contact
# trailblaze.software@gmail.com

# This file configures https://pre-commit.com/
repos:
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        name: CMake Format
        entry: cmake-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.2
    hooks:
      - id: clang-format
  - repo: https://github.com/google/yamlfmt.git
    rev: v0.13.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: mixed-line-ending
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: "Insert license header in source files"
        args:
          - "--detect-license-in-X-top-lines=12"
          - "--license-filepath=license_header.txt"
          - "--comment-style=/*| *| */"
          - "--use-current-year"
        types_or: [c++]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: "Insert license header in source files"
        args:
          - "--detect-license-in-X-top-lines=12"
          - "--license-filepath=license_header.txt"
          - "--use-current-year"
        files: \.txt$|\.cmake$|\.yml$|\.yaml$|\.sh$|\.gitignore$|.clang-format$
        exclude: license_header.txt|LICENSES/.*
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: "Insert license header in source files"
        args:
          - "--detect-license-in-X-top-lines=12"
          - "--license-filepath=license_header.txt"
          - "--use-current-year"
          - "--comment-style=<!--| | -->"
        files: \.md$
